//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.29 at 10:48:26 CST 
//


package com.aspire.doms.ecintf.feedback.vo.BIP4B875T4011136;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MobNum" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Rsp" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RspDesc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "mobNum",
    "rsp",
    "rspDesc"
})
@XmlRootElement(name = "FailInfo")
public class FailInfo {

    @XmlElement(name = "MobNum", required = true)
    protected String mobNum;
    @XmlElement(name = "Rsp", required = true)
    protected String rsp;
    @XmlElement(name = "RspDesc")
    protected String rspDesc;
    @XmlTransient
    protected String oper_seq;

    /**
     * Gets the value of the mobNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMobNum() {
        return mobNum;
    }

    /**
     * Sets the value of the mobNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMobNum(String value) {
        this.mobNum = value;
    }

    /**
     * Gets the value of the rsp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRsp() {
        return rsp;
    }

    /**
     * Sets the value of the rsp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRsp(String value) {
        this.rsp = value;
    }

    /**
     * Gets the value of the rspDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRspDesc() {
        return rspDesc;
    }

    /**
     * Sets the value of the rspDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRspDesc(String value) {
        this.rspDesc = value;
    }

	public String getOper_seq() {
		return oper_seq;
	}

	public void setOper_seq(String operSeq) {
		oper_seq = operSeq;
	}
    
}
