//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.29 at 10:48:26 
//


package com.aspire.doms.ecintf.feedback.vo.BIP4B875T4011136;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.aspire.doms.ecintf.feedback.vo package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.aspire.doms.ecintf.feedback.vo
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SuccInfo }
     * 
     */
    public SuccInfo createSuccInfo() {
        return new SuccInfo();
    }

    /**
     * Create an instance of {@link FailInfo }
     * 
     */
    public FailInfo createFailInfo() {
        return new FailInfo();
    }

    /**
     * Create an instance of {@link UserResult }
     * 
     */
    public UserResult createUserResult() {
        return new UserResult();
    }

}
