//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.29 at 10:48:26
//


package com.aspire.doms.ecintf.feedback.vo.BIP4B875T4011136;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="OperSeq" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SuccNum" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element ref="{}SuccInfo" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="FailNum" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element ref="{}FailInfo" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "operSeq",
    "succNum",
    "succInfo",
    "failNum",
    "failInfo"
})
@XmlRootElement(name = "UserResult")
public class UserResult {

    @XmlElement(name = "OperSeq", required = true)
    protected String operSeq;
    @XmlElement(name = "SuccNum", required = true)
    protected String succNum;
    @XmlElement(name = "SuccInfo")
    protected List<SuccInfo> succInfo;
    @XmlElement(name = "FailNum", required = true)
    protected String failNum;
    @XmlElement(name = "FailInfo")
    protected List<FailInfo> failInfo;
    @XmlTransient
    protected String LHTStatus;
    @XmlTransient
    protected String id;
    @XmlTransient
    protected String ec_id;

    /**
     * Gets the value of the operSeq property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperSeq() {
        return operSeq;
    }

    /**
     * Sets the value of the operSeq property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperSeq(String value) {
        this.operSeq = value;
    }

    /**
     * Gets the value of the succNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSuccNum() {
        return succNum;
    }

    /**
     * Sets the value of the succNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSuccNum(String value) {
        this.succNum = value;
    }

    /**
     * Gets the value of the succInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the succInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSuccInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SuccInfo }
     * 
     * 
     */
    public List<SuccInfo> getSuccInfo() {
        if (succInfo == null) {
            succInfo = new ArrayList<SuccInfo>();
        }
        return this.succInfo;
    }

    /**
     * Gets the value of the failNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFailNum() {
        return failNum;
    }

    /**
     * Sets the value of the failNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFailNum(String value) {
        this.failNum = value;
    }

    /**
     * Gets the value of the failInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the failInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFailInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FailInfo }
     * 
     * 
     */
    public List<FailInfo> getFailInfo() {
        if (failInfo == null) {
            failInfo = new ArrayList<FailInfo>();
        }
        return this.failInfo;
    }

	public String getLHTStatus() {
		return LHTStatus;
	}

	public void setLHTStatus(String lHTStatus) {
		LHTStatus = lHTStatus;
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getEc_id() {
		return ec_id;
	}

	public void setEc_id(String ecId) {
		ec_id = ecId;
	}

}
